apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-sbom-api
  labels:
    app: iis-sbom-api
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: iis-sbom-api
  template:
    metadata:
      labels:
        app: iis-sbom-api
    spec:
      dnsPolicy: "None"
      dnsConfig:
       nameservers:
        - {{ .Values.ticketing.dns.server }}
       searches:
        - {{ .Values.ticketing.dns.domain }}
       options:
        - name: ndots
          value: "2"
        - name: edns0
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sbom-api
        image: pptaz/iis-sbom-api:0.0.6
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command:
              - "c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
              - -command
              - " c:\\PS\\AppendIPAddress.ps1 -pAutoTestPathFile 'D:\\web\\SBOM\\SOMebkOnline.API\\AutoTest\\SOMebkOnline.API.txt' ;"