apiVersion: v1
kind: Service
metadata:
  name: sbom-api
  labels:
    app: sbom-api
spec:
  type: "{{ .Values.serviceType }}"
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: sbom-api
