apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sbom-gui
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/rewrite-target: /SOMebk.GUI/$2

spec:
  ingressClassName: nginx
  rules:
  - host: sbil-api-k8s{{ .Values.ticketing.platform }}.{{ .Values.ticketing.dns.domain }}
    http:
      paths:
      - backend:
          service:
            name: sbom-gui
            port:
              number: 443
        path: /SOMebk.GUI(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - sbil-api-k8s{{ .Values.ticketing.platform }}.{{ .Values.ticketing.dns.domain }}
    secretName: ticketing-wildcard-cert
