apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbom-gui
  labels:
    app: sbom-gui
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: sbom-gui
  template:
    metadata:
      labels:
        app: sbom-gui
    spec:
      dnsPolicy: "None"
      dnsConfig:
       nameservers:
        - {{ .Values.ticketing.dns.server }}
       searches:
        - {{ .Values.ticketing.dns.domain }}
       options:
        - name: ndots
          value: "2"
        - name: edns0
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sbom-gui
        image: pptaz/sbom-gui:0.0.8
        ports:
        - containerPort: 443
        lifecycle:
          postStart:
            exec:
              command:
              - "c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
              - -command
              - " c:\\PS\\AppendIPAddress.ps1 -pAutoTestPathFile 'D:\\web\\SBOM\\SOMebk.GUI\\AutoTest\\SOMebk.GUI.txt' ;"