apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbom-svc
  labels:
    app: sbom-svc
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: sbom-svc
  template:
    metadata:
      labels:
        app: sbom-svc
    spec:
      dnsPolicy: "None"
      dnsConfig:
       nameservers:
        - {{ .Values.ticketing.dns.server }}
       searches:
        - {{ .Values.ticketing.dns.domain }}
       options:
        - name: ndots
          value: "2"
        - name: edns0
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sbom-svc
        image: rancher.kube1.valm:5000/sbom-svc:0.0.6
        ports:
        - containerPort: 80
