apiVersion: v1
kind: Service
metadata:
  name: iis-vad-apis
  labels:
    app: iis-vad-apis
spec:
  type: "{{ .Values.serviceType }}"
  ports:
    # the port that this service should serve on
    - port: 443
      targetPort: 443
  selector:
    app: iis-vad-apis
