apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnano
  labels:
    app: webnano
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: webnano
  template:
    metadata:
      labels:
        app: webnano
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: webnano
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 80